server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: jwt-token-security

  logging:
    level:
      org.springframework.security.web.FilterChainProxy: DEBUG

  datasource:
    url: jdbc:h2:tcp://localhost:9001/~/Documents/PR/SecurityDB
#    url: jdbc:h2:file:~/Documents/PR/SecurityDB
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

  cache:
    jcache:
      config: classpath:ehcache.xml